# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addQuize.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json

class Ui_addQuizeWindow(object):
    def __init__(self,isEdit=False) -> None:
        if not isEdit:
            self.questions={"questions":{},"answers":{},"images":{},"multiple_choice":{}}
        else:
            pass #TODO: add loading from json
        self.isEdit=isEdit

    def setupUi(self, addQuizeWindow):
        addQuizeWindow.setObjectName("addQuizeWindow")
        addQuizeWindow.resize(640, 605)
        addQuizeWindow.setMinimumSize(QtCore.QSize(640, 605))
        addQuizeWindow.setMaximumSize(QtCore.QSize(640, 605))
        self.MainWindow=addQuizeWindow
        self.centralwidget = QtWidgets.QWidget(addQuizeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 621, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_quizeName = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_quizeName.setEnabled(True)
        self.label_quizeName.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        self.label_quizeName.setFont(font)
        self.label_quizeName.setObjectName("label_quizeName")
        self.horizontalLayout_2.addWidget(self.label_quizeName)
        self.lineEdit_quizeName = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.lineEdit_quizeName.setFont(font)
        self.lineEdit_quizeName.setObjectName("lineEdit_quizeName")
        self.horizontalLayout_2.addWidget(self.lineEdit_quizeName)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.pushButton_addQuestion = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_addQuestion.setObjectName("pushButton_addQuestion")
        self.verticalLayout.addWidget(self.pushButton_addQuestion)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtWidgets.QScrollArea(self.verticalLayoutWidget)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 350))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 605, 453))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame = QtWidgets.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./resorces/icons/edit.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setKerning(False)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./resorces/icons/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.horizontalLayout.addLayout(self.verticalLayout_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_cancel.setFont(font)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_3.addWidget(self.pushButton_cancel)
        self.pushButton_save = QtWidgets.QPushButton(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_3.addWidget(self.pushButton_save)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        addQuizeWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(addQuizeWindow)
        self.statusbar.setObjectName("statusbar")
        addQuizeWindow.setStatusBar(self.statusbar)

        #region DEMO
        # self.verticalLayout_DEMO = QtWidgets.QVBoxLayout()
        # self.verticalLayout_DEMO.setObjectName("verticalLayout_DEMO")
        # self.pushButton_edit_DEMO = QtWidgets.QPushButton(self.frame)
        # sizePolicy.setHeightForWidth(self.pushButton_edit_DEMO.sizePolicy().hasHeightForWidth())
        # self.pushButton_edit_DEMO.setSizePolicy(sizePolicy)
        # self.pushButton_edit_DEMO.setMinimumSize(QtCore.QSize(35, 35))
        # self.pushButton_edit_DEMO.setMaximumSize(QtCore.QSize(35, 35))
        # self.pushButton_edit_DEMO.setBaseSize(QtCore.QSize(35, 35))
        # self.pushButton_edit_DEMO.setFont(font)
        # self.pushButton_edit_DEMO.setText("")
        # self.pushButton_edit_DEMO.setIcon(icon)
        # self.pushButton_edit_DEMO.setDefault(False)
        # self.pushButton_edit_DEMO.setObjectName("pushButton_edit_DEMO")
        # self.verticalLayout_5.addWidget(self.pushButton_edit_DEMO)
        # self.pushButton_remove_DEMO = QtWidgets.QPushButton(self.frame)
        # sizePolicy.setHeightForWidth(self.pushButton_remove_DEMO.sizePolicy().hasHeightForWidth())
        # self.pushButton_remove_DEMO.setSizePolicy(sizePolicy)
        # self.pushButton_remove_DEMO.setMinimumSize(QtCore.QSize(35, 35))
        # self.pushButton_remove_DEMO.setMaximumSize(QtCore.QSize(35, 35))
        # self.pushButton_remove_DEMO.setBaseSize(QtCore.QSize(35, 35))
        # self.pushButton_remove_DEMO.setFont(font)
        # self.pushButton_remove_DEMO.setText("")
        # self.pushButton_remove_DEMO.setIcon(icon1)
        # self.pushButton_remove_DEMO.setDefault(False)
        # self.pushButton_remove_DEMO.setObjectName("pushButton_remove_DEMO")
        # self.verticalLayout_5.addWidget(self.pushButton_remove_DEMO)
        # self.label_question_DEMO = QtWidgets.QLabel(self.frame)
        # self.label_question_DEMO.setMinimumSize(QtCore.QSize(500, 90))
        # self.label_question_DEMO.setMaximumSize(QtCore.QSize(500, 16777215))
        # self.label_question_DEMO.setObjectName("label_question_DEMO")
        # self.horizontalLayout.addWidget(self.label_question_DEMO)
        # self.verticalLayout_DEMO.addLayout(self.horizontalLayout)
        # self.horizontalLayout_DEMO = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_DEMO.setObjectName("horizontalLayout_DEMO")
        # self.label_DEMO = QtWidgets.QLabel(self.frame)
        # self.label_DEMO.setMinimumSize(QtCore.QSize(0, 0))
        # self.label_DEMO.setMaximumSize(QtCore.QSize(12, 16777215))
        # self.label_DEMO.setObjectName("label_DEMO")
        # self.horizontalLayout_DEMO.addWidget(self.label_DEMO)
        # self.label_AD_DEMO = QtWidgets.QLabel(self.frame)
        # self.label_AD_DEMO.setMinimumSize(QtCore.QSize(0, 90))
        # self.label_AD_DEMO.setObjectName("label_AD_DEMO")
        # self.horizontalLayout_DEMO.addWidget(self.label_AD_DEMO)
        # self.checkBox_DEMO = QtWidgets.QCheckBox(self.frame)
        # self.checkBox_DEMO.setEnabled(False)
        # self.checkBox_DEMO.setMaximumSize(QtCore.QSize(70, 16777215))
        # self.checkBox_DEMO.setFont(font)
        # self.checkBox_DEMO.setChecked(True)
        # self.checkBox_DEMO.setObjectName("checkBox_DEMO")
        # self.horizontalLayout_DEMO.addWidget(self.checkBox_DEMO)
        # self.verticalLayout_DEMO.addLayout(self.horizontalLayout_DEMO)
        # self.horizontalLayout_DEMO_2 = QtWidgets.QHBoxLayout()
        # self.horizontalLayout_DEMO_2.setObjectName("horizontalLayout_DEMO_2")
        # self.label_DEMO_2 = QtWidgets.QLabel(self.frame)
        # self.label_DEMO_2.setMinimumSize(QtCore.QSize(0, 0))
        # self.label_DEMO_2.setMaximumSize(QtCore.QSize(12, 16777215))
        # self.label_DEMO_2.setObjectName("label_DEMO_2")
        # self.horizontalLayout_DEMO_2.addWidget(self.label_DEMO_2)
        # self.label_AD_DEMO_2 = QtWidgets.QLabel(self.frame)
        # self.label_AD_DEMO_2.setMinimumSize(QtCore.QSize(0, 90))
        # self.label_AD_DEMO_2.setObjectName("label_AD_DEMO_2")
        # self.horizontalLayout_DEMO_2.addWidget(self.label_AD_DEMO_2)
        # self.checkBox_DEMO_2 = QtWidgets.QCheckBox(self.frame)
        # self.checkBox_DEMO_2.setEnabled(False)
        # self.checkBox_DEMO_2.setMaximumSize(QtCore.QSize(70, 16777215))
        # self.checkBox_DEMO_2.setFont(font)
        # self.checkBox_DEMO_2.setChecked(False)
        # self.checkBox_DEMO_2.setObjectName("checkBox_DEMO_2")
        # self.horizontalLayout_DEMO_2.addWidget(self.checkBox_DEMO_2)
        # self.verticalLayout_DEMO.addLayout(self.horizontalLayout_DEMO_2)
        # self.verticalLayout_4.addLayout(self.verticalLayout_DEMO)
        # self.line = QtWidgets.QFrame(self.frame)
        # self.line.setFrameShape(QtWidgets.QFrame.HLine)
        # self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        # self.line.setObjectName("line")
        # self.verticalLayout_4.addWidget(self.line)
        #endregion

        self.retranslateUi(addQuizeWindow)
        QtCore.QMetaObject.connectSlotsByName(addQuizeWindow)

        #button events
        self.pushButton_cancel.clicked.connect(self.closeWindow)
        self.pushButton_save.clicked.connect(self.saveQuize)

    def retranslateUi(self, addQuizeWindow):
        _translate = QtCore.QCoreApplication.translate
        addQuizeWindow.setWindowTitle(_translate("addQuizeWindow", "MainWindow"))
        self.label_quizeName.setText(_translate("addQuizeWindow", "quize name:"))
        self.pushButton_addQuestion.setText(_translate("addQuizeWindow", "add question"))
        #region DEMO TEXT
        # self.label_question_DEMO.setText(_translate("addQuizeWindow", "QUESTION"))
        # self.label_DEMO.setText(_translate("addQuizeWindow", "A)"))
        # self.label_AD_DEMO.setText(_translate("addQuizeWindow", "answer data"))
        # self.checkBox_DEMO.setText(_translate("addQuizeWindow", "answer"))
        # self.label_DEMO_2.setText(_translate("addQuizeWindow", "B)"))
        # self.label_AD_DEMO_2.setText(_translate("addQuizeWindow", "answer data"))
        # self.checkBox_DEMO_2.setText(_translate("addQuizeWindow", "answer"))
        #endregion
        self.pushButton_cancel.setText(_translate("addQuizeWindow", "cancel"))
        self.pushButton_save.setText(_translate("addQuizeWindow", "save"))

    def loadQuestionToUI(self):
        #1)check if self.questios is empty
        #2)VL>HLx2>>X1>LB_question>VL>PB_edit,PB_remove>>X2>CB_answer,LB_a-f,LB_answer>LINE
        #  ^
        #where qustion
        #is holded
        #need to set object name to edit button and remove button (edit_X,remove_X) then split and get the number for action
        #TODO: *** ON REMOVE: loop over the json and decrement the number of the latter questions ***
        pass
        
    def loadQuestions(self):
        print("log i - opening questions")
        #1)open the json of given quize #TODO: add to init quize name from main
        #2)load to question list the questions and answers #TODO: create a function to build based on DEMO the ui
    
    def saveQuize(self):
        print("log i - clicked on save")
        if not len(self.questions)>0:
            print("log e - user is mega dumb and is tring to save a quize without adding questions")
            msg = QtWidgets.QMessageBox()
            msg.setWindowTitle("ERROR T_T")
            msg.setText("must have at least 1 question at your test")
            msg.exec_()
        #TODO: actually save a json
    
    def closeWindow(self):
        print("log i - clicked on close")
        msg = QtWidgets.QMessageBox()
        msg.setStandardButtons(QtWidgets.QMessageBox.Yes | QtWidgets.QMessageBox.Cancel)
        msg.setWindowTitle("exit")
        msg.setText("are you sure you want to exit?")
        msg.exec_()
        if msg.standardButton(msg.clickedButton()) == QtWidgets.QMessageBox.Yes:
            from main import Ui_MainWindow
            ui = Ui_MainWindow()
            ui.setupUi(self.MainWindow)
            self.MainWindow.show()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    addQuizeWindow = QtWidgets.QMainWindow()
    ui = Ui_addQuizeWindow()
    ui.setupUi(addQuizeWindow)
    addQuizeWindow.show()
    sys.exit(app.exec_())
