# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'imageWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Image(object):
    def setupUi(self, MainWindow, img_path):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(579, 432)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(20, 10, 531, 411))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(img_path))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("Question Image", "Question Image"))
