# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QuestionEditWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSlot

class Ui_QuestionEdit(object):
    def setupUi(self, MainWindow, addQuizWindow, q_number):
        # Get Data To Class Instance
        self.addQuizWindow = addQuizWindow
        self.q_number = q_number
        # End Of Our Code Section
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(823, 538)
        font = QtGui.QFont()
        font.setPointSize(20)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 10, 781, 451))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.questionEdit_Vert = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.questionEdit_Vert.setContentsMargins(0, 0, 0, 0)
        self.questionEdit_Vert.setObjectName("questionEdit_Vert")
        self.questionEdit_title = QtWidgets.QHBoxLayout()
        self.questionEdit_title.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.questionEdit_title.setObjectName("questionEdit_title")
        self.titleLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.titleLabel.setMaximumSize(QtCore.QSize(300, 50))
        self.titleLabel.setObjectName("titleLabel")
        self.questionEdit_title.addWidget(self.titleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 1, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.questionEdit_title.addItem(spacerItem)
        self.questionTitleLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.questionTitleLineEdit.setObjectName("questionTitleLineEdit")
        self.questionEdit_title.addWidget(self.questionTitleLineEdit)
        self.questionEdit_Vert.addLayout(self.questionEdit_title)
        # self.answerXHorizontalLayout = QtWidgets.QHBoxLayout()
        # self.answerXHorizontalLayout.setObjectName("answerXHorizontalLayout")
        # self.answerXCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
        # self.answerXCheckBox.setObjectName("answerXCheckBox")
        # self.answerXHorizontalLayout.addWidget(self.answerXCheckBox)
        # self.answerXLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        # self.answerXLineEdit.setObjectName("answerXLineEdit")
        # self.answerXHorizontalLayout.addWidget(self.answerXLineEdit)
        # self.questionEdit_Vert.addLayout(self.answerXHorizontalLayout)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(19, 460, 781, 83))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.buttonHorizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.buttonHorizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.buttonHorizontalLayout.setObjectName("buttonHorizontalLayout")
        self.addAnswerButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.addAnswerButton.setObjectName("addAnswerButton")
        self.buttonHorizontalLayout.addWidget(self.addAnswerButton)
        self.saveButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.saveButton.setObjectName("saveButton")
        self.buttonHorizontalLayout.addWidget(self.saveButton)
        self.cancelButton = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.cancelButton.setObjectName("cancelButton")
        self.buttonHorizontalLayout.addWidget(self.cancelButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.titleLabel.setText(_translate("MainWindow", "Question Title"))
        # self.questionTitleLineEdit.setPlaceholderText(_translate("MainWindow", "example"))
        # self.answerXCheckBox.setText(_translate("MainWindow", "A."))
        # self.answerXLineEdit.setPlaceholderText(_translate("MainWindow", "example"))
        self.addAnswerButton.setText(_translate("MainWindow", "Add Answer"))
        self.saveButton.setText(_translate("MainWindow", "PushButton"))
        self.cancelButton.setText(_translate("MainWindow", "PushButton"))
    
    # Our Code
    def setUpWindow(self):
        self.questionTitleLineEdit.setText(self.addQuizWindow.questions["questions"][str(self.q_number)])
        for i in self.addQuizWindow.questions["answers"][str(self.q_number)].keys():
            answerXHorizontalLayout = QtWidgets.QHBoxLayout()
            answerXHorizontalLayout.setObjectName(f"answer{i}HorizontalLayout")
            answerXCheckBox = QtWidgets.QCheckBox(self.verticalLayoutWidget)
            answerXCheckBox.setObjectName(f"answer{i}CheckBox")
            answerXCheckBox.setText(i+'. ')
            if self.addQuizWindow.questions["answers"][str(self.q_number)][i][0]:
                answerXCheckBox.toggle()
            answerXHorizontalLayout.addWidget(answerXCheckBox)
            answerXLineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
            answerXLineEdit.setObjectName(f"answer{i}LineEdit")
            answerXLineEdit.setText(self.addQuizWindow.questions["answers"][str(self.q_number)][i][0])
            answerXHorizontalLayout.addWidget(answerXLineEdit)
            self.questionEdit_Vert.addLayout(answerXHorizontalLayout)


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_QuestionEdit()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
